name: Gitee repos mirror periodic job
on:
  push:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      #代表我们用的仓库，不用同步
      with:
        # 必选，需要同步的Github用户（源）
        src: github/CatsAndMice
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/CatsAndMice
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}
 
