name: Sync To Gitee  
on: page_build
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:CatsAndMice/medash.git"
          destination-repo: "git@gitee.com:JsHai/tool.git"
      - name: reload
            uses: mizuka-wu/gitee-pages-action@v1.0.0
            with:
                repository: CatsAndMice/medash
                cookie: ${{ secrets.GITEE_COOKIE }} 
                directory: docs
                https: false
